# THE DEGRIBBLER -- READING GRIB FILES
Notebook with code to yoink data from .grib files (data files downloaded from ERA5)


In [36]:
'''misc imports'''
import numpy as np

## Section 1: Data Loading

Download data, and pop it into `../data`

### File Naming
Data will be stored under `../data` with the naming convention:

- Multi-Year (will include all hours): `<attributes>_<start-year>_<end-year>_<region>` 
- Single-Point / Small datasets: `<attributes>_<date>_<time(s)>_<region>`

`<attributes>` will use the short name given in GRIB description or description of properties as a whole // will occasionally be replaced by "full data" OWTTE

### Current data files
For copying and pasting into 'file name' field

- `2d-wind_2024-05-12_all-hours_NA-only` -- 10m u and v wind speeds over North American region (all hours, single day)

In [4]:
'''grab data file names'''
import os

os.listdir('../data')

['2d-wind_2024-05-12_all-hours_NA-only']

**RUN THIS CODE BEFORE ANY FURTHER CODE BLOCKS -- NECESSARY FOR LOADING DATA (AND DEFININING THE `grib_file` VARIABLE)**

In [8]:
'''load grib file'''
import earthkit.data as ekd

FILENAME = '2d-wind_2024-05-12_all-hours_NA-only'

path_ddir = '../data/'
dfile_name = f'{FILENAME}/data.grib'

data_path = path_ddir + dfile_name

grib_file = ekd.from_source('file', data_path)

In [27]:
'''inspect grib file'''

grib_file.ls()

grib_file[0].data().shape

(3, 361, 641)

## 2 - Dataset-specific Code
Storage for code that isn't generally applicable (can probably copy-paste most stuff, but in general, this section is for data validation / cleaning etc)


### 2.1 - WIND DATA

*2d-wind_2024-05-12_all-hours_NA-only* has data points on a 361 x 641 grid

`u_data` and `v_data` have the shapes `(26,361,641)` 

- `data[0]` should be latitudes
- `data[1]` should be longitudes
- `data[2-25]` should then contain the 'values' -- i would guess that (since this is 24 readings) that these are the values for each hour

so for analysis etc, only relevant data is from `data[2:]`

In [ ]:
'''separate data into u, v components'''
# we have values for each variable at each ll coord for each of the 24 hours (24, 361, 641)

ll = grib_file[0].data()[:2] # latitude and longitude at each grid point

u_data = grib_file.sel(shortName='10u').data()[2:]
v_data = grib_file.sel(shortName='10v').data()[2:]

ll.shape

(2, 361, 641)

In [40]:
speed = np.sqrt(u_data**2 + v_data**2)

speed[0]

array([[4.30474332, 4.30474332, 4.30474332, ..., 4.30474332, 4.30474332,
        4.30474332],
       [4.20232934, 4.20051659, 4.19837592, ..., 4.38956492, 4.38983048,
        4.38933561],
       [3.80848158, 3.80736465, 3.80545865, ..., 4.29595155, 4.29410452,
        4.29205443],
       ...,
       [1.54193628, 1.72052247, 1.84326959, ..., 5.63880411, 5.35185068,
        5.1554943 ],
       [2.06151549, 2.14529658, 2.0417061 , ..., 5.33741975, 5.03000506,
        4.84579768],
       [2.51726516, 2.52590904, 2.36311542, ..., 5.12454551, 4.84210093,
        4.64978638]], shape=(361, 641))

In [41]:
u_data[0], v_data[0]

(array([[ 4.23158264,  4.23158264,  4.23158264, ...,  4.23158264,
          4.23158264,  4.23158264],
        [ 3.93373108,  3.92884827,  3.92396545, ..., -4.31040955,
         -4.31236267, -4.31333923],
        [ 3.39076233,  3.38197327,  3.37220764, ..., -4.12095642,
         -4.12388611, -4.1268158 ],
        ...,
        [-1.3611908 , -1.61705017, -1.78013611, ..., -3.71568298,
         -3.48716736, -3.31724548],
        [-1.77720642, -1.93443298, -1.87486267, ..., -3.66197205,
         -3.42076111, -3.23521423],
        [-2.11314392, -2.17466736, -2.06919861, ..., -3.63560486,
         -3.4315033 , -3.24693298]], shape=(361, 641)),
 array([[ 0.79026794,  0.79026794,  0.79026794, ...,  0.79026794,
          0.79026794,  0.79026794],
        [-1.47828674, -1.48609924, -1.49293518, ..., -0.82984924,
         -0.82106018, -0.81324768],
        [-1.73414612, -1.74879456, -1.76344299, ..., -1.21363831,
         -1.19703674, -1.17945862],
        ...,
        [-0.72438049, -0.58766174, -

In [35]:
4.23158264**2

17.90629163914937